3liz/QuickOSM

- README.md
...with link to Etienne's tutorial video, and a few basic steps to get people started
> Add a 'Getting started' section

- README.md
- quick_osm_processing/parser/osm_parser.py
fixes https://github.com/3liz/QuickOSM/issues/40#issuecomment-360135616
Note: the file encoding parameter has been dropped, and I could not find any documentation on `getVectorWriter()` to see what encoding it uses.. 
also minor improvements to the README
> dynamic output format for processing osm parser

- metadata.txt
> version 1.4.8

- metadata.txt
- ui/main_window.py
> follow up bye bye qwebkit

- core/actions.py
- metadata.txt
> remove qwebview from OSM Actions

- core/query_factory.py
- resources/ui/main_window.ui
- ui/quick_query_panel.py
New update from the previous PR, but the friendly message has been added to the QueryFactory.
> Added the friendly message in the QueryFactory.

- README.md
- resources/model/osm_download_style.model3
Example styles can be found here:
https://github.com/anitagraser/QGIS-resources/tree/master/qgis2/osm_spatialite
> Example model to download and style osm from an extent (closes #228)

- .github/workflows/flake8.yml
- .travis.yml
- QuickOSM/core/api/connexion_oapi.py
- QuickOSM/core/process.py
- QuickOSM/core/query_factory.py
- QuickOSM/test/data/overpass/error_decode_utf8.xml
- QuickOSM/test/test_connexion_overpass.py
- QuickOSM/ui/base_overpass_panel.py
- QuickOSM/ui/base_panel.py
- QuickOSM/ui/base_processing_panel.py
- QuickOSM/ui/osm_file_panel.py
- QuickOSM/ui/quick_query_panel.py
- setup.cfg
* Ticket : #240 
* UTF8 - Check the size of the file buffer when reading it
> UTF8 - Check the size of the file buffer when reading it

- QuickOSM/core/api/connexion_oapi.py
* Ticket : #262
* Tested on MacOSX BigSur, QGis 3.18.0
> Fix encoding error (fix #262)

- QuickOSM/core/actions.py
- QuickOSM/core/api/connexion_oapi.py
- QuickOSM/core/api/nominatim.py
- QuickOSM/core/exceptions.py
- QuickOSM/core/parser/osm_parser.py
- QuickOSM/core/process.py
- QuickOSM/core/query_factory.py
- QuickOSM/core/query_preparation.py
- QuickOSM/core/utilities/tools.py
- QuickOSM/quick_osm_processing/advanced/build_query.py
- QuickOSM/quick_osm_processing/advanced/download_overpass.py
- QuickOSM/quick_osm_processing/advanced/open_osm_file.py
- QuickOSM/quick_osm_processing/advanced/raw_query.py
- QuickOSM/quick_osm_processing/provider.py
- QuickOSM/ui/base_overpass_panel.py
- QuickOSM/ui/base_panel.py
- QuickOSM/ui/base_processing_panel.py
- QuickOSM/ui/custom_ui.py
- QuickOSM/ui/dialog.py
- QuickOSM/ui/osm_file_panel.py
- QuickOSM/ui/query_panel.py
- QuickOSM/ui/quick_query_panel.py
- QuickOSM/ui/xml_highlighter.py
- requirements-dev.txt
* I have added some python annotation in the files. Let me know if you saw some that I missed
> Python Annotation

- QuickOSM/core/api/nominatim.py
- QuickOSM/core/query_preparation.py
- QuickOSM/definitions/nominatim.py
- QuickOSM/resources/ui/main_window.ui
- QuickOSM/test/test_configuration_panel.py
- QuickOSM/ui/configuration_panel.py
> Choice of Nominatim Server

- QuickOSM/core/actions.py
* Fix mapillary action, the action appeared even without a field 'mapillary' in the attribute table
> Fix Mapillary Action

- QuickOSM/ui/base_overpass_panel.py
> Fix bug #243

- QuickOSM/core/api/connexion_oapi.py
- QuickOSM/core/api/nominatim.py
- QuickOSM/core/exceptions.py
- QuickOSM/test/test_connexion_nominatim.py
- QuickOSM/test/test_connexion_overpass.py
* Build of tests about the connection to the nominatim API 
* Fix of the around functionality : search "around the Tower Eiffel" was providing coordinates in Ukraine
> Nominatim connexion test, fix around query type

- QuickOSM/core/api/connexion_oapi.py
- QuickOSM/core/process.py
- QuickOSM/core/query_factory.py
- QuickOSM/core/query_preparation.py
- QuickOSM/definitions/osm.py
- QuickOSM/resources/ui/main_window.ui
- QuickOSM/test/test_main_window_dialog.py
- QuickOSM/test/test_query_factory.py
- QuickOSM/test/test_query_preparation.py
- QuickOSM/ui/base_overpass_panel.py
- QuickOSM/ui/dialog.py
- QuickOSM/ui/query_panel.py
- QuickOSM/ui/quick_query_panel.py
* First step for #284
* A view of the change panel :
> Generation of OQL  #284

- QuickOSM/quick_osm.py
- QuickOSM/test/test_configuration_panel.py
- QuickOSM/test/test_main_window_dialog.py
- QuickOSM/test/test_overpass_panel.py
- QuickOSM/ui/dialog.py
> Tests - Avoid using get_iface and start_app in tests

- QuickOSM/core/exceptions.py
- QuickOSM/core/process.py
- QuickOSM/resources/ui/main_window.ui
- QuickOSM/test/test_overpass_panel.py
- QuickOSM/ui/base_overpass_panel.py
- QuickOSM/ui/dialog.py
- QuickOSM/ui/query_panel.py
- QuickOSM/ui/quick_query_panel.py
* Ticket : fix #45
* I have added an option to choose only the extent of the selected features in a layer.
* I'll build some test next week
> Add option selected features for layer #45

- QuickOSM/ui/xml_highlighter.py
* Ticket : #25 
* Highlighter updated for the oql language 
View of an oql query
> Highlighter for oql #25

- QuickOSM/ui/base_processing_panel.py
> Fix disable of output dir #310

- QuickOSM/core/parser/preset_parser.py
- QuickOSM/resources/ui/main_window.ui
- QuickOSM/test/test_preset_parser.py
- QuickOSM/ui/quick_query_panel.py
* Ticket : #206 
* First step for a parser of the default_presets file
> Presets parser #206

- QuickOSM/core/actions.py
- QuickOSM/core/parser/osm_parser.py
- QuickOSM/core/process.py
- QuickOSM/core/query_preparation.py
- QuickOSM/definitions/action.py
- QuickOSM/definitions/osm.py
- QuickOSM/ui/dialog.py
* Ticket : #291 
* Add an action to reload the query
> Relaunch a query in a new file #291

- QuickOSM/core/process.py
- QuickOSM/definitions/format.py
- QuickOSM/resources/ui/main_window.ui
- QuickOSM/ui/base_processing_panel.py
- QuickOSM/ui/dialog.py
- QuickOSM/ui/osm_file_panel.py
- QuickOSM/ui/query_panel.py
- QuickOSM/ui/quick_query_panel.py
* Ticket : fix #311 
* Add a combo box for the choice of the output format
> Choice of output format #311

- QuickOSM/core/process.py
* I have added a builder of qml file in order to use the field colour provided by OSM
> Retrieval of color from OSM data

- QuickOSM/core/query_factory.py
- QuickOSM/quick_osm_processing/advanced/build_query.py
* Ticket : #321 
* A changed function was call, one argument missed
> Processing Fix #321

- QuickOSM/ui/query_panel.py
* The generation wouldn't work when there was no layer in the project
> Fix generation of a query

- QuickOSM/core/process.py
- QuickOSM/quick_osm.py
- QuickOSM/resources/ui/main_window.ui
* Ticket : #313 
* Add a popup at the end of the process to inform the user of the use of the OSM copyright
> Copyright popup #313

- .docker/docker-compose-qgis.yml
- QuickOSM/core/parser/osm_parser.py
- QuickOSM/core/process.py
- QuickOSM/core/utilities/extent_tool.py
- QuickOSM/core/utilities/json_encoder.py
- QuickOSM/core/utilities/query_saved.py
- QuickOSM/core/utilities/tools.py
- QuickOSM/definitions/osm.py
- QuickOSM/metadata.txt
- QuickOSM/resources/ui/edit_bookmark.ui
- QuickOSM/resources/ui/main_window.ui
- QuickOSM/test/test_saved_query.py
- QuickOSM/ui/base_processing_panel.py
- QuickOSM/ui/edit_bookmark.py
- QuickOSM/ui/query_panel.py
- QuickOSM/ui/quick_query_panel.py
- setup.cfg
* I have added the option to save a query and a historic is automatically saved.
* I'm still thinking about what will the ui look like...
> History and bookmark of queries

- QuickOSM/core/parser/osm_parser.py
- QuickOSM/core/query_factory.py
- QuickOSM/quick_osm_processing/advanced/build_query.py
- QuickOSM/quick_osm_processing/advanced/decorate_output.py
- QuickOSM/quick_osm_processing/advanced/open_osm_file.py
- QuickOSM/quick_osm_processing/advanced/raw_query.py
- QuickOSM/quick_osm_processing/build_input.py
- QuickOSM/quick_osm_processing/provider.py
- QuickOSM/quick_osm_processing/quickosm_process.py
- QuickOSM/test/test_processing.py
* Ticket : #210 
* I have begin some work about the QuickOSM processing algorithms.
> Add and rework of processing algorithms

- QuickOSM/core/parser/osm_parser.py
- QuickOSM/core/process.py
- QuickOSM/quick_osm_processing/quickosm_process.py
- QuickOSM/resources/ui/main_window.ui
- QuickOSM/ui/base_processing_panel.py
- QuickOSM/ui/dialog.py
* Ticket : fix #10 
* We can now cancel a process while running
> Cancel process from main window

- QuickOSM/core/parser/osm_parser.py
- QuickOSM/core/process.py
- QuickOSM/resources/ui/main_window.ui
- QuickOSM/test/test_file_panel.py
- QuickOSM/test/test_main_window_dialog.py
- QuickOSM/test/test_osm_parser.py
- QuickOSM/test/test_saved_query.py
- QuickOSM/ui/custom_table.py
- QuickOSM/ui/dialog.py
- QuickOSM/ui/osm_file_panel.py
- QuickOSM/ui/quick_query_panel.py
* Ticket : fix #208 
* I have added an option to select features when loading a local osm file
> Add an option to subset the features while loading an OSM file

- .docker/code_doc.sh
- .docker/processing_doc.sh
- Makefile
- QuickOSM/core/actions.py
- QuickOSM/core/api/connexion_oapi.py
- QuickOSM/core/api/nominatim.py
- QuickOSM/core/query_factory.py
- QuickOSM/core/utilities/tools.py
- docs/code-documentation/core.md
- docs/code-documentation/definitions.md
- docs/code-documentation/developer.md
- docs/code-documentation/processing.md
- docs/code-documentation/tests.md
- docs/code-documentation/ui.md
- docs/media/code.css
- mkdocs.yml
- requirements/doc.txt
Generation of the python documentation
> Doc python

- QuickOSM/core/exceptions.py
- QuickOSM/core/parser/preset_parser.py
- QuickOSM/resources/ui/main_window.ui
- QuickOSM/test/test_preset_parser.py
- QuickOSM/test/test_processing.py
- QuickOSM/test/test_saved_query.py
- QuickOSM/ui/custom_table.py
- QuickOSM/ui/map_preset_panel.py
* Some adjustments before the 2.0.0 release
> Adjustments 2.0.0

- QuickOSM/resources/map_preset/Urban/Urban_Road_lines.qml
* Ticket : fix #377 
Before: 
After:
> Add trunk roads to Urban visualization preset

- QuickOSM/quick_osm_processing/advanced/decorate_output.py
fix a small typo in the output decoration of processing that gives a stack trace
> Fix error in Processing algorithm

- README.md
The twitter profile seems defunct.
Noticed this because I was curious. I hope I found the correct Mastodon/Fediverse account, @Gustry.
> Update author link
